"""Configuration for company RAG software"""
import os
from enum import Enum
from dotenv import load_dotenv

load_dotenv()

class FileExtensions(Enum):
    CSV = ".csv"
    PDF = ".pdf"
    TXT = ".txt"

class LLMType(Enum):
    OPENAI = "openai"

class EmbeddingsType(Enum):
    OPENAI = "openai"
    
# Constants for RAG system configuration
DATA_DIRECTORY = "./data" # Contatins all company documents which will be processed
COMPANY_KNOWLEDGE_COLLECTION = "company_knowledge"
PERSISTENT_DB_PATH = "./chroma_db"  # Persistent database path
FILE_METADATA_PATH = "./file_metadata.json"  # File tracking metadata to update embeddings after a file is changed
MAX_TOKENS = 800 # Determines the lenghth of the response generated by the LLM
TEMPERATURE = 0 # Determines the creativity of the response generated by the LLM, 0 means deterministic, not creative at all
TOP_K_RESULTS = 2 # Top most relevant references from documents to be returned
MAX_RELEVANCE_DISTANCE = 0.55 

# PDF processing
PDF_CHUNK_SIZE = 1000  
PDF_OVERLAP = 200      

# Model configuration constants
OPENAI_EMBEDDING_MODEL = "text-embedding-ada-002"
OPENAI_LLM_MODEL = "gpt-4o-mini"
OPENAI_API_KEY_ENV_VAR = "OPENAI_API_KEY"

os.environ["TOKENIZERS_PARALLELISM"] = "false"
